# Generated by Django 5.2 on 2025-04-15 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('max_participants', models.IntegerField()),
                ('message_template', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.CharField(blank=True, choices=[('fund_incomplete', 'Fundamental Incompleto'), ('fund_complete', 'Fundamental Completo'), ('med_incomplete', 'Médio Incompleto'), ('med_complete', 'Médio Completo'), ('sup_incomplete', 'Superior Incompleto'), ('sup_complete', 'Superior Completo')], max_length=20, null=True)),
                ('study_period', models.CharField(blank=True, choices=[('morning', 'Manhã'), ('afternoon', 'Tarde'), ('night', 'Noite'), ('integral', 'integral')], max_length=20, null=True)),
                ('desired_course', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BatchAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.batch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('delivered', 'Entregue'), ('read', 'Lido'), ('failed', 'Falhou'), ('received', 'Recebida')], default='pending', max_length=20)),
                ('wamid', models.CharField(blank=True, help_text='ID da mensagem WhatsApp para rastreamento de status', max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userregistration')),
            ],
        ),
    ]
